import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	

	return (
		<div>
			<Head>
				<title>Go Fiber + MySQL CRUD</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='flex flex-col items-center pt-8'>
				<h1 className='mb-8'>Go Todo App</h1>
				<form>
					<div className='my-2'>
						<label className='block' htmlFor='task_name'>
							Task:
						</label>
						<input className='px-2 py-1' type='text' name='task' />
					</div>
					<div className='my-2'>
						<label className='block' htmlFor='owner_name'>
							Owner:
						</label>
						<input className='px-2 py-1' type='text' name='task' />
					</div>
					<div className='pt-2'>
						<label htmlFor='status'></label>
						<select name='status' onChange={e => console.log(e.target.value)}>
							<option value='false'>false</option>
							<option value='true'>true</option>
						</select>
					</div>
				</form>
			</main>
		</div>
	);
};

export default Home;
